openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    <опис вашого додатку>
tags:
  - name: Contacts
    description: Operations about contacts.
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-r1ls.onrender.com
paths:
  /contacts:
    get: 
      $ref: ../swagger/path/contacts/get.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/path/contacts/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
